import { LevelConfig } from '../types/game';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'El Despertar del Río Inírida',
    subtitle: 'Navegación inicial en aguas calmas',
    landmark: 'Puerto Inírida · Muelle de las Curiaras',
    description: 'Aprende a coordinar los remos de madera por las aguas oscuras del río Inírida esquivando troncos y piedras lisas.',
    lore: 'El río Inírida es conocido por sus aguas de color té oscuro, ricas en taninos de las hojas de la selva virgen. Los indígenas curripaco tallan curiaras de troncos de cedro amargo.',
    targetDistance: 700,
    riverWidth: 700,
    riverCurrent: 160,
    obstacleSpawnRate: 1.8,
    whirlpoolChance: 0.1,
    animalTypes: [],
    weather: 'SUNNY',
    waterColor: '#122525',
    waterCurrentColor: '#1a3835',
    backgroundTepuis: false,
    rewardTitle: 'Timonel del Inírida',
  },
  {
    id: 2,
    name: 'Caño Bocón y los Caimanes',
    subtitle: 'Aguas profundas y fauna al acecho',
    landmark: 'Boca del Caño Bocón',
    description: 'El cauce se estrecha entre la espesura. Caimanes negros descansan y patrullan las orillas esperando cualquier descuido.',
    lore: 'El Caimán Negro del Orinoco y Amazonas puede superar los 4 metros. En Guainía son respetados como guardianes silenciosos de los caños profundos.',
    targetDistance: 900,
    riverWidth: 640,
    riverCurrent: 180,
    obstacleSpawnRate: 2.2,
    whirlpoolChance: 0.15,
    animalTypes: ['caiman'],
    weather: 'MIST',
    waterColor: '#15241f',
    waterCurrentColor: '#1f3b32',
    backgroundTepuis: false,
    rewardTitle: 'Ojo de Cazador',
  },
  {
    id: 3,
    name: 'El Abrazo del Remolino',
    subtitle: 'Corrientes giratorias en Caño San Joaquín',
    landmark: 'Meandros de San Joaquín',
    description: 'Grandes vórtices succionan todo a su paso. Si quedas atrapado, rema con fuerza hacia el exterior para escapar de su fuerza.',
    lore: 'Los ancianos puinaves advierten que en los remolinos habita el espíritu del agua que prueba la sincronía y la serenidad de los remeros.',
    targetDistance: 1100,
    riverWidth: 620,
    riverCurrent: 200,
    obstacleSpawnRate: 2.5,
    whirlpoolChance: 0.45,
    animalTypes: ['caiman'],
    weather: 'SUNNY',
    waterColor: '#10272b',
    waterCurrentColor: '#163d42',
    backgroundTepuis: false,
    rewardTitle: 'Domador de Vórtices',
  },
  {
    id: 4,
    name: 'Raudales de Guainía (Aguas Bravas)',
    subtitle: 'Velocidad vertiginosa entre peñascos',
    landmark: 'Raudal de Zamuro',
    description: 'La corriente se acelera drásticamente formando espuma blanca y arrojando la canoa hacia rocas afiladas de granito.',
    lore: 'Navegar un raudal exige calcular el vector de empuje del agua contra el peso de la curiara. Un solo roce puede partir el casco.',
    targetDistance: 1300,
    riverWidth: 600,
    riverCurrent: 260,
    obstacleSpawnRate: 2.8,
    whirlpoolChance: 0.35,
    animalTypes: [],
    weather: 'RAIN',
    waterColor: '#0f2930',
    waterCurrentColor: '#1c4d59',
    backgroundTepuis: false,
    rewardTitle: 'Espíritu de las Aguas Bravas',
  },
  {
    id: 5,
    name: 'El Paso de las Pirañas Rojas',
    subtitle: 'Cardúmenes voraces en aguas rojizas',
    landmark: 'Remanso de los Pavones',
    description: 'Bancos de pirañas saltan y atacan todo movimiento brusco. Mantén el rumbo constante para no caer en su frenesí.',
    lore: 'La piraña roja amazónica posee mandíbulas capaces de cortar alambres. Se congregan cuando el nivel del río cambia bruscamente.',
    targetDistance: 1500,
    riverWidth: 580,
    riverCurrent: 220,
    obstacleSpawnRate: 3.0,
    whirlpoolChance: 0.3,
    animalTypes: ['piranha'],
    weather: 'SUNSET',
    waterColor: '#261b17',
    waterCurrentColor: '#422820',
    backgroundTepuis: false,
    rewardTitle: 'Guardián del Cardumen',
  },
  {
    id: 6,
    name: 'Laguna del Brujo y la Gran Anaconda',
    subtitle: 'Misterio ancestral en la selva profunda',
    landmark: 'Laguna Negra del Brujo',
    description: 'Aguas calmas pero densas de niebla. Monstruosas anacondas de río cruzan serpenteando entre los juncos y remolinos ocultos.',
    lore: 'Para los pueblos del Guainía, la anaconda (Yuruparí) es el origen de los ríos y de los cantos sagrados del mundo selvático.',
    targetDistance: 1750,
    riverWidth: 600,
    riverCurrent: 210,
    obstacleSpawnRate: 3.2,
    whirlpoolChance: 0.4,
    animalTypes: ['anaconda', 'caiman'],
    weather: 'MIST',
    waterColor: '#0b1f24',
    waterCurrentColor: '#14363e',
    backgroundTepuis: false,
    rewardTitle: 'Aliado de la Serpiente de Agua',
  },
  {
    id: 7,
    name: 'El Cañón de Granito y Vientos Selva',
    subtitle: 'Garganta rocosa y corrientes cruzadas',
    landmark: 'Estrecho de las Rocas Negras',
    description: 'El río se comprime en un cañón estrecho flanqueado por altos riscos de roca negra precámbrica. Los remolinos son gemelos.',
    lore: 'El escudo guayanés es una de las formaciones geológicas más antiguas del planeta, con rocas de más de 1.700 millones de años.',
    targetDistance: 2000,
    riverWidth: 520,
    riverCurrent: 270,
    obstacleSpawnRate: 3.5,
    whirlpoolChance: 0.5,
    animalTypes: ['caiman'],
    weather: 'STORM',
    waterColor: '#0d181c',
    waterCurrentColor: '#172f38',
    backgroundTepuis: false,
    rewardTitle: 'Conquistador del Cañón',
  },
  {
    id: 8,
    name: 'Estrella Fluvial del Inírida',
    subtitle: 'Confluencia sagrada de tres ríos',
    landmark: 'Punto Trirrefugio · Atabapo, Guaviare e Inírida',
    description: 'Las aguas negras, blancas y rojas chocan creando una corriente turbulenta inestable habitada por caimanes gigantes y pirañas.',
    lore: 'La Estrella Fluvial de Inírida es sitio Ramsar de importancia planetaria, donde confluyen ecosistemas de la Orinoquía y la Amazonía.',
    targetDistance: 2250,
    riverWidth: 680,
    riverCurrent: 280,
    obstacleSpawnRate: 3.7,
    whirlpoolChance: 0.45,
    animalTypes: ['piranha', 'caiman'],
    weather: 'GOLDEN_HOUR',
    waterColor: '#1c1b12',
    waterCurrentColor: '#36341e',
    backgroundTepuis: true,
    rewardTitle: 'Navegante de la Estrella Fluvial',
  },
  {
    id: 9,
    name: 'El Gran Raudal de Mapiripana',
    subtitle: 'La prueba de la furia fluvial',
    landmark: 'Garganta de Mapiripana',
    description: 'El raudal más imponente y traicionero. Bloques colosales de roca, torbellinos múltiples y pirañas en aguas espumosas.',
    lore: 'Mapiripana es temido por todos los boteros del Guainía. Solo los indígenas más experimentados logran franquearlo sin zozobrar.',
    targetDistance: 2600,
    riverWidth: 560,
    riverCurrent: 320,
    obstacleSpawnRate: 4.2,
    whirlpoolChance: 0.55,
    animalTypes: ['anaconda', 'piranha'],
    weather: 'STORM',
    waterColor: '#122026',
    waterCurrentColor: '#244857',
    backgroundTepuis: true,
    rewardTitle: 'Maestro de Mapiripana',
  },
  {
    id: 10,
    name: 'Los Sagrados Cerros de Mavecure',
    subtitle: 'La cima mística de la Amazonía',
    landmark: 'Santuario de Mavicure, Mono y Pajarito',
    description: 'Los majestuosos monolitos de granito negro se alzan en el horizonte. Supera el tramo final para consagrar tu viaje legendario.',
    lore: 'Los Cerros de Mavecure son tepuyes sagrados para la cosmogonía indígena. Llegar a sus faldas en curiara es un rito de inmortalidad fluvial.',
    targetDistance: 3000,
    riverWidth: 650,
    riverCurrent: 290,
    obstacleSpawnRate: 4.0,
    whirlpoolChance: 0.5,
    animalTypes: ['caiman', 'anaconda', 'piranha'],
    weather: 'GOLDEN_HOUR',
    waterColor: '#17221d',
    waterCurrentColor: '#2c473c',
    backgroundTepuis: true,
    rewardTitle: 'Leyenda Sagrada del Guainía',
  },
];
